spring:
  application:
    name: insurance-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/labcabrera/lab-insurance-cloud-config

server:
  port: 8888

security:
  basic:
    enabled: false

management:
  security:
    enabled: false
    
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'