# lab-insurance

image:https://travis-ci.org/labcabrera/lab-insurance.svg?branch=master["Build Status", link="https://travis-ci.org/labcabrera/lab-insurance"]

= Insurance Showcase Engine

Motor de gestión de productos de ahorro basado en una arquitectura de microservicios con las siguientes
características.

Su desarrollo se basa en:

* Spring Boot
* Spring Integration
* RabbitMQ
* Spring Cloud Netflix
* MongoDB

== Contratación

La contratación está separada en dos módulos. Un gateway que simplemente provee de los servicios REST
comunes que hace de dispatcher para encolar los mensajes en RabbitMQ.

Después tenemos el otro módulo que procesa los mensajes obtenidos de RabbitMQ.

Flujo:

* El cliente realiza una llamada al servicio rest prepare a partir de unos parámetros generales tales
como el tipo de contrato (acuerdo marco). El servicio devuelve un objeto `ContractCreationData`.
* En segundo lugar el cliente invoca al servicio de contratación pasando ese objeto una vez se
ha completado con la información requerida.
* El gateway lo enruta, y si la validación es correcta se encola en RabbitMQ.
* El módulo de integración recibe el mensaje y lo procesa, volcando el resultado a RabbitMQ.
** Adicionalmente publica los eventos también a través de AMQP para que los diferentes módulos
efectúen las diferentes acciones necesarias (generación de documentación, initialización de los
portfolios, etc).
* El gateway recupera la información del contrato y genera la respuesta.

== Development

=== Ejecutando el proyecto

Una vez montado el proyecto deberemos arrancar mongodb y rabbitmq. Para ello en la carpeta
_/docker/env_ hay un docker-compose.

Si utilizamos la configuración de Spring Cloud Config deberemos arrancar también el servidor
de configuración. Podemos hacerlo también desde el docker-compose específico o arrancándolo
desde nuestro IDE.

Después tenemos el proyecto BDD donde tenemos stories de diferentes operativas. Para poder
ejecutar los stories será necesario tener levantados los diversos módulos que hacen falta.

Por ejemplo para el storie básico de contratación necesitaremos primero ejecutar la
aplicación `ContractCreationCoreApp` y posteriormente ejecutaremos el
test `ContractCreationCucumberTest`. 

=== Configuración de colas

[Pendiente de documentar]

Aunque se puede ejecutar sin crear colas persistentes se recomienda crear las siguientes colas
desde la interface de administración de RabbitMQ (por defecto con las credenciales guest:guest):

http://localhost:15672/#/queues

=== Nomenclatura de los módulos:

Los módulos _${name}-core_ hacen referencia a proyectos de integración sin interface web.
Los módulos _${name}-gateway_ hacen referencia a los módulos web que generalmente explotan los servicios core
utilizando AMQP.

=== Local port mapping

|===
|cloud-config               | 8888
|eureka                     | 8070
|zuul-gateway               | 8080
|contract-creation-gateway  | 8081
|legal-entity-gateway       | 8082
|asset-gateway              | 8089
|accounting-gateway         | 8083
|contract-common-gateway    | 8091
|===

== References

=== Spring Integration

* https://github.com/spring-projects/spring-integration-java-dsl/wiki/spring-integration-java-dsl-reference
* https://spring.io/blog/2014/11/25/spring-integration-java-dsl-line-by-line-tutorial
* https://github.com/bijukunjummen/si-dsl-rabbit-sample
* https://knallisworld.de/blog/2016/03/26/expose-a-java-method-with-amqp-and-spring-reloaded-with-java-dsl/
