spring:
#  profiles:
#    active: local
  application:
    name: insurance-contract-creation-core

---
spring:
  profiles: local
  data:
    mongodb:
      uri: mongodb://localhost:27017/lab-insurance

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/


management:
  context-path: /admin
  security:
    enabled: false

logging:
  level.org: INFO