#TODO pasar a cloud config

configuration:
  projectName: insurance-zuul

spring:
  application:
    name: insurance-zuul
  thymeleaf:
    #no cache templates under development phase
    cache: false

zuul:
  prefix: /api
  routes:
    # Error: eureka discovery dont resove server list (see issues):
    asset:
      path: /assets/**
      url: http://localhost:8090/
    order:
      path: /orders/**
      url: http://localhost:8091/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

#ribbon:
#  eureka:
#    enabled: true

#ribbon:
#  eureka:
#   enabled: true
#    ReadTimeout: 20000
#    ConnectTimeout: 20000

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

management:
  context-path: /admin
  security.enabled: false

logging:
level.org: INFO